baseURL = 'https://www.reprozurich.org/'
languageCode = 'en-gb'
title = 'Design and Analysis of Replication Studies'
theme = 'devfest-theme-hugo'

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

[params]
    title = "Reproducibility day 2023"
    date = "2023-02-09"
    description = "The reproducibility day is a one-day conference dedicated to the promotion of open and reproducible research."
    images = ["/images/social-share.jpg"]
    email = "crs@ebpi.uzh.ch"
    keywords = "event, crs, reproducibility, conference"
    copyright = "This website was built using Hugo and the devfest theme"
    copyright_link = "https://github.com/felix-hof/reprozuerich"
    subscriptionUrl = "https://ebpi.lists.uzh.ch/sympa/subscribe/crs"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#168e51"

[params.logos]
    #jumbo = "/images/logos/logo_large.png"
    header = "/images/logos/CRS_logo_green_with_border.png"
    footer = "/images/logos/CRS_logo_green_with_border.png"

[languages]
[languages.en]
    weight = 1
    languageName = "gb"

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

